"""Add user_id to StudentFeeRecord

Revision ID: c7d8743eb617
Revises: cfbdb8f6f0d6
Create Date: 2025-07-25 18:21:38.835296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d8743eb617'
down_revision: Union[str, Sequence[str], None] = 'cfbdb8f6f0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
